services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./log:/log
    restart: always
    
  webserver:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

