services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./Api/user.log:/app/user.log

  webserver:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./WebApp:/usr/share/nginx/html  

