
FROM nginx
# Copy the custom configuration file to override the default one
COPY default.conf /etc/nginx/conf.d/default.conf
# Copy your site content into the container
COPY . /usr/share/nginx/html
ENV TZ="America/New_York"

